services:
  etcdapp:
    image: etcdapp
    build: ./etcdapp
    container_name: etcdapp
    ports:
      - "5076:5076"
      - "6076:6076"
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd --advertise-client-urls=http://0.0.0.0:2379 --listen-client-urls=http://0.0.0.0:2379
    volumes:
      - ~/volumes/data/etcd:/data.etcd
    ports:
      - "2379:2379"